export const COUNTRIES_DATA = [
  // Asia & South Asia
  { name: "India",           iso: "in", code: "+91"  },
  { name: "China",           iso: "cn", code: "+86"  },
  { name: "Japan",           iso: "jp", code: "+81"  },
  { name: "South Korea",     iso: "kr", code: "+82"  },
  { name: "Pakistan",        iso: "pk", code: "+92"  },
  { name: "Bangladesh",      iso: "bd", code: "+880" },
  { name: "Philippines",     iso: "ph", code: "+63"  },
  { name: "Indonesia",       iso: "id", code: "+62"  },
  { name: "Malaysia",        iso: "my", code: "+60"  },
  { name: "Singapore",       iso: "sg", code: "+65"  },
  { name: "Thailand",        iso: "th", code: "+66"  },
  { name: "Vietnam",         iso: "vn", code: "+84"  },
  { name: "Myanmar",         iso: "mm", code: "+95"  },
  { name: "Nepal",           iso: "np", code: "+977" },
  { name: "Sri Lanka",       iso: "lk", code: "+94"  },
  { name: "Afghanistan",     iso: "af", code: "+93"  },
  { name: "Cambodia",        iso: "kh", code: "+855" },
  { name: "Taiwan",          iso: "tw", code: "+886" },
  { name: "Hong Kong",       iso: "hk", code: "+852" },
  // Middle East
  { name: "UAE",             iso: "ae", code: "+971" },
  { name: "Saudi Arabia",    iso: "sa", code: "+966" },
  { name: "Israel",          iso: "il", code: "+972" },
  { name: "Turkey",          iso: "tr", code: "+90"  },
  { name: "Iran",            iso: "ir", code: "+98"  },
  { name: "Iraq",            iso: "iq", code: "+964" },
  { name: "Jordan",          iso: "jo", code: "+962" },
  { name: "Lebanon",         iso: "lb", code: "+961" },
  { name: "Kuwait",          iso: "kw", code: "+965" },
  { name: "Qatar",           iso: "qa", code: "+974" },
  { name: "Bahrain",         iso: "bh", code: "+973" },
  { name: "Oman",            iso: "om", code: "+968" },
  // Europe
  { name: "United Kingdom",  iso: "gb", code: "+44"  },
  { name: "Germany",         iso: "de", code: "+49"  },
  { name: "France",          iso: "fr", code: "+33"  },
  { name: "Italy",           iso: "it", code: "+39"  },
  { name: "Spain",           iso: "es", code: "+34"  },
  { name: "Portugal",        iso: "pt", code: "+351" },
  { name: "Netherlands",     iso: "nl", code: "+31"  },
  { name: "Belgium",         iso: "be", code: "+32"  },
  { name: "Switzerland",     iso: "ch", code: "+41"  },
  { name: "Sweden",          iso: "se", code: "+46"  },
  { name: "Norway",          iso: "no", code: "+47"  },
  { name: "Denmark",         iso: "dk", code: "+45"  },
  { name: "Finland",         iso: "fi", code: "+358" },
  { name: "Poland",          iso: "pl", code: "+48"  },
  { name: "Ukraine",         iso: "ua", code: "+380" },
  { name: "Russia",          iso: "ru", code: "+7"   },
  { name: "Romania",         iso: "ro", code: "+40"  },
  { name: "Greece",          iso: "gr", code: "+30"  },
  { name: "Czech Republic",  iso: "cz", code: "+420" },
  { name: "Hungary",         iso: "hu", code: "+36"  },
  { name: "Austria",         iso: "at", code: "+43"  },
  { name: "Ireland",         iso: "ie", code: "+353" },
  // Americas
  { name: "United States",   iso: "us", code: "+1"   },
  { name: "Canada",          iso: "ca", code: "+1"   },
  { name: "Mexico",          iso: "mx", code: "+52"  },
  { name: "Brazil",          iso: "br", code: "+55"  },
  { name: "Argentina",       iso: "ar", code: "+54"  },
  { name: "Colombia",        iso: "co", code: "+57"  },
  { name: "Chile",           iso: "cl", code: "+56"  },
  { name: "Peru",            iso: "pe", code: "+51"  },
  { name: "Venezuela",       iso: "ve", code: "+58"  },
  { name: "Ecuador",         iso: "ec", code: "+593" },
  { name: "Bolivia",         iso: "bo", code: "+591" },
  { name: "Paraguay",        iso: "py", code: "+595" },
  { name: "Uruguay",         iso: "uy", code: "+598" },
  // Oceania
  { name: "Australia",       iso: "au", code: "+61"  },
  { name: "New Zealand",     iso: "nz", code: "+64"  },
  // Africa
  { name: "Nigeria",         iso: "ng", code: "+234" },
  { name: "Egypt",           iso: "eg", code: "+20"  },
  { name: "South Africa",    iso: "za", code: "+27"  },
  { name: "Kenya",           iso: "ke", code: "+254" },
  { name: "Ethiopia",        iso: "et", code: "+251" },
  { name: "Ghana",           iso: "gh", code: "+233" },
  { name: "Tanzania",        iso: "tz", code: "+255" },
  { name: "Uganda",          iso: "ug", code: "+256" },
  { name: "Morocco",         iso: "ma", code: "+212" },
  { name: "Algeria",         iso: "dz", code: "+213" },
  { name: "Cameroon",        iso: "cm", code: "+237" },
  { name: "Ivory Coast",     iso: "ci", code: "+225" },
  { name: "Senegal",         iso: "sn", code: "+221" },
  { name: "Rwanda",          iso: "rw", code: "+250" },
  { name: "Zimbabwe",        iso: "zw", code: "+263" },
  { name: "Zambia",          iso: "zm", code: "+260" },
].sort((a, b) => a.name.localeCompare(b.name));

/** Curated skill suggestions shown in Primary & Secondary autocomplete. */
export const SKILL_OPTIONS = [
  "Python", "JavaScript", "TypeScript", "React", "Node.js",
  "SQL", "Machine Learning", "Data Analysis", "Data Visualization",
  "Excel", "PowerBI", "Tableau", "R", "MATLAB",
  "UX Design", "UI Design", "Figma", "Adobe XD", "Sketch",
  "Graphic Design", "Video Editing", "Motion Graphics", "Illustration",
  "Content Writing", "Copywriting", "SEO", "Social Media", "Email Marketing",
  "Research", "Market Research", "Competitive Analysis",
  "Project Management", "Scrum", "Agile", "JIRA", "Asana",
  "Financial Modelling", "Accounting", "Business Analysis",
  "Quality Assurance", "Automation Testing", "Selenium",
  "Translation", "Transcription", "Proofreading",
  "Customer Support", "CRM", "Salesforce",
  "DevOps", "Docker", "Kubernetes", "CI/CD",
  "Cybersecurity", "Penetration Testing", "Cloud (AWS)", "Cloud (GCP)", "Cloud (Azure)",
].sort();

export const TIMEZONES = [
  "Asia/Kolkata (IST +5:30)",
  "Asia/Dhaka (BST +6:00)",
  "Asia/Karachi (PKT +5:00)",
  "Asia/Colombo (SLST +5:30)",
  "Asia/Kathmandu (NPT +5:45)",
  "Asia/Tokyo (JST +9:00)",
  "Asia/Seoul (KST +9:00)",
  "Asia/Singapore (SGT +8:00)",
  "Asia/Shanghai (CST +8:00)",
  "Asia/Bangkok (ICT +7:00)",
  "Asia/Jakarta (WIB +7:00)",
  "Asia/Dubai (GST +4:00)",
  "Asia/Riyadh (AST +3:00)",
  "Africa/Nairobi (EAT +3:00)",
  "Africa/Lagos (WAT +1:00)",
  "Africa/Johannesburg (SAST +2:00)",
  "Europe/London (GMT +0:00)",
  "Europe/Berlin (CET +1:00)",
  "Europe/Paris (CET +1:00)",
  "Europe/Moscow (MSK +3:00)",
  "America/New_York (EST -5:00)",
  "America/Chicago (CST -6:00)",
  "America/Denver (MST -7:00)",
  "America/Los_Angeles (PST -8:00)",
  "America/Toronto (EST -5:00)",
  "America/Vancouver (PST -8:00)",
  "America/Sao_Paulo (BRT -3:00)",
  "America/Mexico_City (CST -6:00)",
  "Pacific/Auckland (NZST +12:00)",
  "Australia/Sydney (AEST +10:00)",
  "Australia/Melbourne (AEST +10:00)",
  "UTC (UTC +0:00)",
];

export const REGISTRATION_STEPS = ["Identity", "Verification", "Profile", "Consent"] as const;
